name: CI/CD PNPM Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
          run_install: false # Disable auto-install to customize steps

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: pnpm install

      # Step 4: Build Project
      - name: Build Project
        run: pnpm run build

      # Step 5: Run Tests
      - name: Run Tests
        run: pnpm run test
